services:
  directus:
    image: directus/directus:11.1.0
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      DB_CLIENT: "pg"
      DB_CONNECTION_STRING: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
      ADMIN_EMAIL: "${ADMIN_EMAIL}"
      ADMIN_PASSWORD: "${ADMIN_PW}"
      SECRET: "${SECRET}"
      WEBSOCKETS_ENABLED: "true"
      WEBSOCKETS_GRAPHQL_ENABLED: "false"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - general

  postgres:
    image: postgres:16.4
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}  
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - general
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 50s
      timeout: 10s
      retries: 5

volumes:
  pgdata:

networks:
  general:
    driver: bridge