services:
  postgresdb:
    image: postgres:17.1
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "6432:5432"
    volumes:
      - pgdata2:/var/lib/postgresql/data
    networks:
      - general
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 50s
      timeout: 10s
      retries: 5
  payload:
    image: faustdp/dock:payload-shnyaga
    environment:
      - DATABASE_URI=${DATABASE_URI}
      - PAYLOAD_SECRET=${PAYLOAD_SECRET}
    ports:
      - "5777:5777"
    expose:
      - "5777"
    networks:
      - general
    restart: unless-stopped
    depends_on:
      postgresdb:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5777/api/health || exit 1"] 
      interval: 60s
      timeout: 10s
      retries: 5
  shnyaga:
    image: faustdp/dock:shnyaga
    build:
      context: .
    ports:
      - "5773:5773"
    expose:
      - "5773"
    depends_on:
      postgresdb:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - BOT_TOKEN=${BOT_TOKEN}
      - SITE_URL=${SITE_URL}
      - SETUP_SECRET=${SETUP_SECRET}
      - PUBLIC_SITE_URL=${PUBLIC_SITE_URL}
      - PUBLIC_TEST_URL=${PUBLIC_TEST_URL}
      - PUBLIC_SITE_PORT=${PUBLIC_SITE_PORT}
      - PUBLIC_BOT_NAME=${PUBLIC_BOT_NAME}
      - PUBLIC_BOT_APPNAME=${PUBLIC_BOT_APPNAME}
      - PUBLIC_NODE_ENV=${PUBLIC_NODE_ENV}
      - PUBLIC_BUGSNAG_KEY=${PUBLIC_BUGSNAG_KEY}
      - BUGSNAG_KEY_NODE=${BUGSNAG_KEY_NODE}
      - SERVER_ID=first
    networks:
      - general
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5773/api/health || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
volumes:
  pgdata2:
networks:
  general:
    driver: bridge